### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by doubleangels** [Benhgift/work_time_percent_applet#10]
Could be pretty easy to make a version for Mac using something like [rumps](https://github.com/jaredks/rumps).

**Comment by Benhgift** [comment]
That would be awesome. I don't have a Mac to test it on, but love the idea

**Comment by doubleangels** [comment]
Alright, let's get a functional version out for Ubuntu and then I will port the code over for a Mac version. :)

**Comment by Benhgift** [comment]
#13 added support for it, give it a try! :+1:
