### ISSUE TITLE
Requirements.txt doesn't contain all requirements for mac version

### ISSUE THREAD

**Issue by doubleangels** [Benhgift/work_time_percent_applet#14]
After running `pip install -r requirements.txt`, the Mac version still required `rumps` and `Foundation` installed.

**Comment by mtverlee** [comment]
After running `pip install -r requirements.txt`, the Mac version still required `rumps` and `Foundation` installed.

**Comment by Benhgift** [comment]
The problem is that that package doesn't install on Ubuntu (pip errors on it). So if we put it in the `requirements.txt` then it'll break the Ubuntu side. 

It might make sense to have an `osx_requirements.txt` too

**Comment by Benhgift** [comment]
Alternatively it might make sense to remove the requirements files and just have a `setup.py` which checks the OS. But doing that would make it so vitrual-env wouldn't work (right?)

**Comment by jpinsonault** [comment]
This might help: http://stackoverflow.com/questions/16011379/operating-system-specific-requirements-with-pip

Once this gets turned into a package
