### ISSUE TITLE
Error going from 20:00 to 4:00

### ISSUE THREAD

**Issue by Benhgift** [Benhgift/work_time_percent_applet#5]
This needs to be fixed for night workers.

**Comment by doubleangels** [comment]
Can you provide a little more information about the error? I'd like to take a look at it. :)

**Comment by Benhgift** [comment]
Sure :) if you're a night worker and your work day goes from 20:00 to 4:00 in the morning, then this doesn't work. You can test it by running the applet in that range with `python3 main.py 20 4`

**Comment by doubleangels** [comment]
I'm not seeing any issues with running `python3 main.py 20 4` as mentioned.

```
matt@Ubuntu-VM:~/work_time_percent_applet$ python3 main.py 20 4
main.py:9: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
main.py:11: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
```
There are the warnings about versions obviously if that's what you mean. :)
I could also just be missing something as I am running on low sleep at this point. What error are you getting?

Thanks!

**Comment by Benhgift** [comment]
Oh sorry, I'm not getting an error, it just isn't working. If the first number is bigger than the second one (in the case of someone whose workday goes past midnight) then it just doesn't work and always displays 0.000%

**Comment by Benhgift** [comment]
I added a unit test that shows the problem, you can run `pytest` from the directory to run it

**Comment by doubleangels** [comment]
That's strange. Your unit test appears to not work for me. Also, if I run the applet using `python3 main.py 20 4` and it is not yet 8pm, it does show zero until 8pm (which I simulate by advancing my system time), at which point it jumps to 100%. Additonally, if the current time is between 5pm and 6pm and I run the applet using `python3 main.py 17 1`, it just jumps straight to 100%, as outlined [here](https://github.com/Benhgift/work_time_percent_applet/issues/7).

**Comment by Benhgift** [comment]
Oh the test should fail, but once the bug is fixed the test will pass. As for actually fixing the bug, I'm not sure how yet

**Comment by Benhgift** [comment]
Fixed in https://github.com/Benhgift/work_time_percent_applet/commit/dfb0b6e39fc95c725da4515532adb4b960c88cf4

But the fix is kinda ugly, refactoring would be good
